### ISSUE TITLE
Error on Linux Mint 18.1 Serena

### ISSUE THREAD

**Issue by daniel020403** [vaibhav-sidapara/vagrant-manager#4]
Hello,

I get an error shown in the attached image below when starting the app.
Below is my environment:

- Using Linux Mint 18.1 Serena.
- Virtualbox installed.
- Vagrant installed.
- No vagrant boxes created yet.

![error_001](https://user-images.githubusercontent.com/709746/26963759-cd621118-4d20-11e7-86c4-56720783e08a.png)

Appreciate a quick response.

Cheers!

**Comment by vaibhav-sidapara** [comment]
Hi @daniel020403 ,

Thank you for acknowledging the issue.

Apparently, you have answered your own question.

> No vagrant boxes created yet.

Vagrant Manager tries to read the status of the boxes from an index file which is generated by the Vagrant itself. Since you have not initiated any box, the index file is missing and hence it shows this error. 

If you create at least one box the error will be solved.

I will put a validation check if the file exists in the next commit so that the error doesn't occur.

Thank you.
